


export const Action_MOVIE_Types={
    MOVIE_LOAD:"MOVIE_LOAD",
    MOVIE_SUCCESS:"MOVIE_SUCCESS",
    MOVIE_ERROR:"MOVIE_ERROR",
    MOVIE_ADD_LIST:"MOVIE_ADD_LIST",
    REMOVE_FROM_LIST:"REMOVE_FROM_LIST"
}


